import itertools
import os
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from utils.logger import setup_logger
from config.settings import Settings

logger = setup_logger(__name__)


class TrieNode:
    __slots__ = ("children", "is_end")

    def __init__(self):
        self.children: Dict[str, "TrieNode"] = {}
        self.is_end = False


class WordFinder:
    def __init__(self, settings: Settings):
        self.settings = settings
        self._trie = TrieNode()
        self._word_count = 0

    def load_dictionary(self, wordlist_path: Optional[str] = None) -> None:
        words_loaded = 0

        if wordlist_path and Path(wordlist_path).exists():
            with open(wordlist_path, encoding="utf-8", errors="ignore") as f:
                for line in f:
                    word = line.strip().upper()
                    if self._valid_word(word):
                        self._insert(word)
                        words_loaded += 1
            logger.info("Loaded %d words from %s", words_loaded, wordlist_path)
            self._word_count = words_loaded
            return

        self._load_builtin()

    def _valid_word(self, word: str) -> bool:
        min_len = self.settings.boggle.min_word_length
        max_len = self.settings.boggle.max_word_length
        return min_len <= len(word) <= max_len and word.isalpha()

    def _insert(self, word: str) -> None:
        node = self._trie
        for ch in word:
            if ch not in node.children:
                node.children[ch] = TrieNode()
            node = node.children[ch]
        node.is_end = True

    def _load_builtin(self) -> None:
        words = {
            # 3-letter
            "ACE", "ACT", "ADD", "AGE", "AGO", "AID", "AIM", "AIR", "ALL",
            "AND", "ANT", "ANY", "APE", "ARC", "ARE", "ARK", "ARM", "ART",
            "ASH", "ASK", "ATE", "AWE", "AXE", "BAD", "BAG", "BAN", "BAR",
            "BAT", "BED", "BET", "BIG", "BIT", "BOW", "BOX", "BOY", "BUD",
            "BUG", "BUN", "BUS", "BUT", "BUY", "CAB", "CAM", "CAN", "CAP",
            "CAR", "CAT", "COP", "COT", "COW", "CRY", "CUB", "CUP", "CUT",
            "DAD", "DAM", "DAY", "DEN", "DEW", "DID", "DIG", "DIM", "DIP",
            "DOG", "DOT", "DRY", "DUB", "DUD", "DUE", "DUG", "DUN", "DUO",
            "DYE", "EAR", "EAT", "EEL", "EGG", "ELF", "ELM", "EMU", "END",
            "ERA", "EVE", "EWE", "EYE", "FAN", "FAR", "FAT", "FAX", "FED",
            "FEE", "FEW", "FIG", "FIN", "FIR", "FIT", "FLY", "FOB", "FOE",
            "FOG", "FOR", "FOX", "FRO", "FRY", "FUN", "FUR", "GAP", "GAS",
            "GAY", "GEL", "GEM", "GET", "GIG", "GIN", "GNU", "GOD", "GOT",
            "GUM", "GUN", "GUT", "GUY", "GYM", "HAD", "HAM", "HAS", "HAT",
            "HAY", "HEN", "HER", "HEW", "HEX", "HID", "HIM", "HIP", "HIS",
            "HIT", "HOG", "HOP", "HOT", "HOW", "HUB", "HUE", "HUG", "HUM",
            "HUT", "ICE", "ICY", "ILL", "IMP", "INK", "INN", "ION", "IRE",
            "IRK", "ITS", "IVY", "JAB", "JAM", "JAR", "JAW", "JAY", "JET",
            "JIG", "JOB", "JOG", "JOT", "JOY", "JUG", "KEN", "KEY", "KID",
            "KIT", "LAB", "LAD", "LAG", "LAP", "LAW", "LAY", "LEA", "LED",
            "LEG", "LET", "LID", "LIE", "LIP", "LIT", "LOG", "LOT", "LOW",
            "MAD", "MAN", "MAP", "MAR", "MAT", "MAY", "MEN", "MET", "MID",
            "MIX", "MOB", "MOM", "MOP", "MUD", "MUG", "NAB", "NAG", "NAP",
            "NET", "NEW", "NIL", "NIT", "NOD", "NOR", "NOT", "NOW", "NUN",
            "NUT", "OAK", "OAR", "OAT", "ODD", "OFF", "OFT", "OIL", "OLD",
            "ONE", "OPT", "ORB", "ORE", "OUR", "OUT", "OWE", "OWL", "OWN",
            "PAD", "PAL", "PAN", "PAP", "PAT", "PAW", "PAY", "PEA", "PEG",
            "PEN", "PET", "PIE", "PIG", "PIN", "PIT", "PLY", "POD", "POP",
            "POT", "PRO", "PUB", "PUG", "PUN", "PUP", "PUT", "QUIT", "RAG",
            "RAM", "RAN", "RAP", "RAT", "RAW", "RAY", "RED", "REF", "RIB",
            "RID", "RIG", "RIM", "RIP", "ROB", "ROD", "ROT", "ROW", "RUB",
            "RUG", "RUN", "RUT", "RYE", "SAC", "SAD", "SAG", "SAP", "SAT",
            "SAW", "SAY", "SEA", "SET", "SEW", "SHE", "SHY", "SIN", "SIP",
            "SIR", "SIS", "SIT", "SIX", "SKI", "SKY", "SLY", "SOB", "SOD",
            "SON", "SOP", "SOT", "SOW", "SOY", "SPA", "SPY", "STY", "SUB",
            "SUM", "SUN", "TAB", "TAG", "TAN", "TAP", "TAR", "TAX", "TEA",
            "TEN", "THE", "THY", "TIE", "TIN", "TIP", "TOE", "TON", "TOO",
            "TOP", "TOW", "TOY", "TRY", "TUB", "TUG", "TWO", "URN", "USE",
            "VAN", "VAT", "VET", "VEX", "VIA", "VIEW", "VOW", "WAD", "WAR",
            "WAS", "WAX", "WAY", "WEB", "WED", "WET", "WHO", "WHY", "WIG",
            "WIN", "WIT", "WOE", "WOK", "WON", "WOO", "WOW", "YAM", "YAP",
            "YAW", "YEA", "YES", "YET", "YEW", "YOU", "ZAP", "ZEN", "ZIP",
            "ZOO",
            # 4-letter
            "ABLE", "ACHE", "ACID", "ACME", "ACRE", "ALSO", "ARCH", "AREA",
            "ARK", "AVID", "BACK", "BALE", "BALL", "BAND", "BARE", "BARK",
            "BARN", "BASE", "BEACH", "BEAD", "BEAK", "BEAM", "BEAN", "BEAR",
            "BEAU", "BED", "BELL", "BEND", "BIAS", "BIKE", "BILE", "BIND",
            "BIRD", "BITE", "BLUE", "BLUR", "BOAT", "BODY", "BOLD", "BOLT",
            "BOMB", "BOND", "BONE", "BOOK", "BOOM", "BOOT", "BORE", "BOSS",
            "BOWL", "BRED", "BREE", "BREW", "BRIM", "BROW", "BULB", "BULK",
            "BULL", "BUMP", "BURN", "BURY", "BUSH", "BUSY", "BUTT", "BUZZ",
            "CAGE", "CAKE", "CALF", "CALL", "CALM", "CAME", "CAMP", "CANT",
            "CARD", "CARE", "CART", "CASH", "CAST", "CAVE", "CEIL", "CELL",
            "CENT", "CHAF", "CHAP", "CHAR", "CHAT", "CHEW", "CHIC", "CHIN",
            "CHIP", "CHOP", "CITE", "CLAD", "CLAM", "CLAN", "CLAP", "CLIP",
            "CLOP", "CLOT", "CLUB", "CLUE", "COAL", "COAT", "CODE", "COIL",
            "COIN", "COLD", "COLT", "COMB", "COME", "CONE", "COOK", "COOL",
            "COPE", "CORD", "CORE", "CORK", "CORN", "COST", "COVE", "COWL",
            "CRAB", "CRAG", "CRAM", "CREW", "CROP", "CROW", "CRUD", "CUFF",
            "CULT", "CURB", "CURE", "CURF", "CURL", "CURT", "CUSP", "CUTE",
            "DALE", "DAME", "DAMP", "DARE", "DARK", "DART", "DASH", "DATE",
            "DAWN", "DEAD", "DEAF", "DEAL", "DEAN", "DEAR", "DEBT", "DECK",
            "DECO", "DEED", "DEEM", "DEEP", "DEER", "DEFT", "DEMO", "DENT",
            "DENY", "DESK", "DIAL", "DICE", "DIET", "DIME", "DINE", "DIRE",
            "DIRT", "DISC", "DISH", "DISK", "DOCK", "DOES", "DOLL", "DOME",
            "DONE", "DOOM", "DOOR", "DOSE", "DOVE", "DOWN", "DOZE", "DRAB",
            "DRAG", "DRAM", "DRAW", "DREW", "DRIP", "DROP", "DRUM", "DUAL",
            "DUCK", "DUCT", "DUEL", "DUET", "DUKE", "DULL", "DUMP", "DUNE",
            "DUNK", "DUST", "DUTY", "DYED", "DYKE", "EACH", "EARN", "EASE",
            "EAST", "EASY", "EDGE", "EDIT", "ELSE", "EMIT", "EPIC", "ESPY",
            "EVEN", "EVIL", "EXAM", "EXIT", "FACE", "FACT", "FADE", "FAIL",
            "FAIR", "FAKE", "FALL", "FAME", "FANG", "FARE", "FARM", "FAST",
            "FATE", "FAWN", "FEAR", "FEAT", "FEED", "FEEL", "FEET", "FELL",
            "FELT", "FEND", "FERN", "FEST", "FEUD", "FIEF", "FILE", "FILM",
            "FIND", "FINE", "FIRE", "FIRM", "FISH", "FIST", "FLAG", "FLAT",
            "FLED", "FLEE", "FLEW", "FLIP", "FLIT", "FLOG", "FLOP", "FLOW",
            "FOAM", "FOLD", "FOLK", "FOND", "FONT", "FOOD", "FOOL", "FOOT",
            "FORD", "FORE", "FORK", "FORM", "FORT", "FOUL", "FOUR", "FREE",
            "FROG", "FROM", "FUEL", "FULL", "FUME", "FUND", "FURY", "FUSE",
            "GAIN", "GALE", "GAME", "GAPE", "GASH", "GASP", "GATE", "GAVE",
            "GAZE", "GEAR", "GELD", "GIFT", "GILD", "GILL", "GILT", "GIRL",
            "GIST", "GIVE", "GLAD", "GLOW", "GLUE", "GLUT", "GNAT", "GNUS",
            "GOAD", "GOAT", "GOLD", "GOLF", "GONE", "GONG", "GOOD", "GORE",
            "GOWN", "GRAB", "GRAM", "GRAY", "GREW", "GRID", "GRIM", "GRIN",
            "GRIP", "GROW", "GRUB", "GUFF", "GULL", "GULP", "GURU", "GUST",
            "GUTS", "HACK", "HAIL", "HAIR", "HALE", "HALF", "HALL", "HALT",
            "HAME", "HAND", "HANG", "HARD", "HARM", "HARP", "HART", "HATE",
            "HAUL", "HAVE", "HEAD", "HEAL", "HEAP", "HEAR", "HEAT", "HEEL",
            "HEIR", "HELD", "HELL", "HELM", "HELP", "HERB", "HERD", "HERE",
            "HERO", "HIDE", "HIGH", "HIKE", "HILL", "HILT", "HIND", "HINT",
            "HIRE", "HISS", "HIVE", "HOOD", "HOOF", "HOOK", "HOPE", "HORN",
            "HOSE", "HOST", "HOUR", "HOWL", "HUGE", "HULL", "HUMN", "HUNG",
            "HUNK", "HURT", "HUSH", "HYMN", "ICED", "ICON", "IDEA", "IDLE",
            "IDOL", "INCH", "INTO", "IRON", "ISLE", "ITCH", "ITEM", "JACK",
            "JAIL", "JAZZ", "JEAN", "JEEP", "JEST", "JEWS", "JOB", "JOGS",
            "JOKE", "JURY", "JUST", "KEEN", "KEEP", "KEEL", "KEPT", "KICK",
            "KIDS", "KILL", "KIND", "KING", "KISS", "KITE", "KNEE", "KNEW",
            "KNIT", "KNOB", "KNOT", "KNOW", "LACE", "LACK", "LAID", "LAKE",
            "LAMP", "LAND", "LANE", "LARK", "LASH", "LASS", "LAST", "LATE",
            "LAWN", "LEAD", "LEAF", "LEAN", "LEAP", "LEFT", "LEND", "LENS",
            "LESS", "LIAR", "LICK", "LIFE", "LIFT", "LIKE", "LIMB", "LIME",
            "LIMP", "LINE", "LINK", "LION", "LIST", "LIVE", "LOAD", "LOAF",
            "LOAN", "LOCK", "LOFT", "LOGO", "LONE", "LONG", "LOOK", "LOOM",
            "LOOP", "LORD", "LORE", "LOSE", "LOSS", "LOST", "LOUD", "LOVE",
            "LUCK", "LUMP", "LUNG", "LURE", "LURK", "LUSH", "MACE", "MADE",
            "MAGI", "MAID", "MAIL", "MAIN", "MAKE", "MALE", "MALL", "MALT",
            "MANE", "MANY", "MARE", "MARK", "MASK", "MAST", "MATE", "MAZE",
            "MEAL", "MEAN", "MEAT", "MEET", "MELD", "MELT", "MEMO", "MEND",
            "MENU", "MERE", "MESH", "MILD", "MILK", "MILL", "MIME", "MIND",
            "MINE", "MINT", "MISS", "MIST", "MOAT", "MOCK", "MODE", "MOLD",
            "MOLE", "MOLL", "MOLT", "MONK", "MOOD", "MOON", "MOSS", "MOST",
            "MOTH", "MOVE", "MUCH", "MUCK", "MUFF", "MULE", "MUSE", "MUSH",
            "MUST", "MUTE", "MYTH", "NAIL", "NAME", "NAPE", "NARY", "NAVE",
            "NEAR", "NEAT", "NECK", "NEED", "NEON", "NEST", "NEWS", "NEWT",
            "NICE", "NINE", "NODE", "NONE", "NOON", "NORM", "NOSE", "NOTE",
            "NOUN", "NUDE", "NUTS", "OATH", "OBEY", "ODOR", "OILY", "OKAY",
            "ONCE", "ONLY", "ONTO", "OOZE", "OPAL", "OPEN", "ORAL", "OVAL",
            "OVEN", "OVER", "OXEN", "PACE", "PACK", "PAGE", "PAID", "PAIL",
            "PAIN", "PAIR", "PALE", "PALM", "PANE", "PARK", "PART", "PASS",
            "PAST", "PATH", "PAVE", "PAWN", "PAYS", "PEAK", "PEAL", "PEAR",
            "PEAS", "PECK", "PEEL", "PEER", "PELF", "PELT", "PEND", "PERK",
            "PEST", "PHOT", "PIAN", "PICK", "PIER", "PIKE", "PILE", "PILL",
            "PINE", "PINK", "PINT", "PION", "PIPE", "PLAN", "PLAY", "PLEA",
            "PLED", "PLOP", "PLOT", "PLOW", "PLOY", "PLUG", "PLUM", "PLUS",
            "POKE", "POLE", "POLL", "POLO", "POND", "PONY", "POOL", "POOR",
            "POPE", "PORK", "PORT", "POSE", "POST", "POUR", "PRAY", "PREY",
            "PROD", "PROP", "PROW", "PULL", "PULP", "PUMP", "PUNK", "PURE",
            "PURL", "PURR", "PUSH", "PUTT", "QUAD", "QUIT", "QUIZ", "RACE",
            "RACK", "RAFT", "RAGE", "RAID", "RAIL", "RAIN", "RAKE", "RAMP",
            "RANG", "RANK", "RANT", "RARE", "RASH", "RASP", "RATE", "RAVE",
            "READ", "REAL", "REAP", "REAR", "RECK", "REED", "REEF", "REEL",
            "REIN", "REND", "RENT", "REST", "RICE", "RICH", "RIDE", "RIFT",
            "RILE", "RING", "RIOT", "RIPE", "RISE", "RISK", "ROAD", "ROAM",
            "ROAR", "ROBE", "ROCK", "RODE", "ROLE", "ROLL", "ROOF", "ROOM",
            "ROOT", "ROPE", "ROSE", "ROSS", "ROSY", "ROTE", "ROUT", "ROVE",
            "RUCK", "RUDE", "RUFF", "RUGS", "RUIN", "RULE", "RUNG", "RUNT",
            "RUSE", "RUST", "RUTH", "SACK", "SAFE", "SAGA", "SAGE", "SAID",
            "SAIL", "SAKE", "SALE", "SALT", "SAME", "SAMP", "SAND", "SANE",
            "SANG", "SANK", "SAVE", "SCAB", "SCAM", "SCAN", "SCAR", "SCAT",
            "SCOT", "SEAL", "SEAM", "SEAR", "SEAT", "SEED", "SEEK", "SEEM",
            "SEEN", "SELF", "SELL", "SEND", "SENT", "SEPT", "SERE", "SERF",
            "SETS", "SEWN", "SHAG", "SHED", "SHIN", "SHIP", "SHOD", "SHOE",
            "SHOP", "SHOT", "SHOW", "SHUT", "SICK", "SIDE", "SIFT", "SIGH",
            "SIGN", "SILK", "SILL", "SILT", "SING", "SINK", "SIRE", "SITE",
            "SIZE", "SKID", "SKIM", "SKIN", "SKIP", "SLAB", "SLAM", "SLAP",
            "SLAT", "SLAW", "SLAY", "SLED", "SLEW", "SLID", "SLIM", "SLIP",
            "SLIT", "SLOB", "SLOP", "SLOT", "SLOW", "SLUG", "SLUM", "SLUR",
            "SMOG", "SNAP", "SNIP", "SNUG", "SOAK", "SOAP", "SOAR", "SOCK",
            "SODA", "SOFA", "SOIL", "SOLD", "SOLE", "SOLO", "SOME", "SONG",
            "SOON", "SORE", "SORT", "SOUL", "SOUR", "SOWN", "SPAM", "SPAN",
            "SPAR", "SPEC", "SPED", "SPEW", "SPIN", "SPIT", "SPOT", "SPRY",
            "SPUD", "SPUR", "STAB", "STAG", "STAR", "STAY", "STEM", "STEW",
            "STIR", "STOP", "STUB", "STUD", "STUN", "SUCH", "SUIT", "SULK",
            "SUMP", "SUNG", "SUNK", "SURE", "SURF", "SWAB", "SWAM", "SWAN",
            "SWAP", "SWIM", "TABS", "TACK", "TACT", "TAGS", "TAIL", "TAKE",
            "TALE", "TALK", "TALL", "TAME", "TANK", "TAPE", "TARN", "TARP",
            "TASK", "TASTE", "TAXI", "TEAM", "TEAR", "TEEN", "TELL", "TEMP",
            "TEND", "TENT", "TERM", "TEST", "TEXT", "THAN", "THAT", "THEM",
            "THEN", "THEY", "THIN", "THIS", "THUD", "THUS", "TICK", "TIDE",
            "TIDY", "TIED", "TIER", "TILE", "TILL", "TILT", "TIME", "TINE",
            "TINT", "TINY", "TIRE", "TOAD", "TOIL", "TOLD", "TOLL", "TOMB",
            "TONE", "TOOK", "TOOL", "TOOT", "TORE", "TORN", "TOSS", "TOUR",
            "TOWN", "TRAP", "TRAY", "TREE", "TREK", "TRIM", "TRIO", "TRIP",
            "TROD", "TROT", "TRUE", "TUBE", "TUCK", "TUFT", "TUNA", "TUNE",
            "TURN", "TWIG", "TWIN", "TWIT", "TYPE", "UGLY", "UNDO", "UNIT",
            "UNTO", "UPON", "URGE", "USED", "USER", "VAIN", "VALE", "VANE",
            "VARY", "VASE", "VAST", "VEIL", "VEIN", "VENT", "VERB", "VERY",
            "VEST", "VETO", "VICE", "VIEW", "VINE", "VOID", "VOLT", "VOTE",
            "WADE", "WAFT", "WAGE", "WAIL", "WAIT", "WAKE", "WALK", "WALL",
            "WAND", "WANT", "WARD", "WARM", "WARN", "WARP", "WARS", "WARY",
            "WASH", "WAST", "WAVE", "WAVY", "WAXY", "WEAK", "WEAL", "WEAN",
            "WEAR", "WEED", "WEEK", "WEEP", "WELL", "WENT", "WERE", "WEST",
            "WHAT", "WHEN", "WHIM", "WHIP", "WHOM", "WICK", "WIDE", "WIFE",
            "WILD", "WILL", "WILT", "WILY", "WIND", "WINE", "WING", "WINK",
            "WIPE", "WIRE", "WIRY", "WISE", "WISH", "WIST", "WITS", "WOAD",
            "WOES", "WOKE", "WOLF", "WOMB", "WOND", "WOOD", "WOOL", "WORD",
            "WORE", "WORK", "WORM", "WORN", "WOVE", "WRAP", "WREN", "WRIT",
            "WROK", "YANK", "YARD", "YARN", "YEAR", "YELL", "YOGA", "YOKE",
            "YOLK", "YORE", "YOUNG", "YOUR", "ZEAL", "ZERO", "ZINC", "ZONE",
            # 5-letter
            "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT",
            "ADULT", "AFTER", "AGAIN", "AGENT", "AGREE", "ALARM", "ALBUM",
            "ALERT", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLEY", "ALLOW",
            "ALONE", "ALONG", "ALTER", "ANGEL", "ANGER", "ANGLE", "ANGRY",
            "APART", "APPLE", "APPLY", "ARENA", "ARGUE", "ARISE", "ARRAY",
            "ASIDE", "ASSET", "AVOID", "AWARD", "AWARE", "BADLY", "BAKER",
            "BASIC", "BASIN", "BASIS", "BATCH", "BEACH", "BEAST", "BENCH",
            "BIRTH", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLAST",
            "BLAZE", "BLEED", "BLEND", "BLESS", "BLIND", "BLINK", "BLISS",
            "BLOCK", "BLOOD", "BLOOM", "BOARD", "BONUS", "BOOTH", "BOUND",
            "BRAIN", "BRAND", "BRAVE", "BREAD", "BREAK", "BREED", "BRICK",
            "BRIEF", "BRING", "BROAD", "BROKE", "BROOK", "BUILD", "BUILT",
            "BUNCH", "BURST", "CABIN", "CABLE", "CANDY", "CARRY", "CATCH",
            "CAUSE", "CEASE", "CHAIN", "CHAIR", "CHARM", "CHART", "CHASE",
            "CHEAP", "CHECK", "CHEEK", "CHEER", "CHESS", "CHEST", "CHIEF",
            "CHILD", "CHINA", "CIVIL", "CLAIM", "CLASS", "CLEAN", "CLEAR",
            "CLERK", "CLICK", "CLIFF", "CLIMB", "CLING", "CLOCK", "CLONE",
            "CLOSE", "CLOTH", "CLOUD", "CLOWN", "COACH", "COAST", "COLOR",
            "COMET", "COMMA", "CORAL", "COUCH", "COUNT", "COURT", "COVER",
            "CRACK", "CRAFT", "CRASH", "CRAWL", "CRAZY", "CREAM", "CREEK",
            "CREST", "CRICK", "CRIME", "CRISP", "CROSS", "CROWD", "CROWN",
            "CRUEL", "CRUSH", "CRUST", "CURVE", "CYCLE", "DAIRY", "DANCE",
            "DEBUT", "DECAY", "DELAY", "DELTA", "DENSE", "DEPTH", "DERBY",
            "DESERT", "DESIGN", "DESIRE", "DEVIL", "DIARY", "DIGIT", "DINER",
            "DIRTY", "DOUBT", "DOUGH", "DOZEN", "DRAFT", "DRAIN", "DRAKE",
            "DRAMA", "DRANK", "DRAWN", "DREAM", "DRESS", "DRIED", "DRIFT",
            "DRILL", "DRINK", "DRIVE", "DROVE", "DROWN", "DRUNK", "EAGER",
            "EAGLE", "EARLY", "EARTH", "EIGHT", "ELBOW", "ELDER", "ELECT",
            "ELITE", "EMPTY", "ENACT", "ENEMY", "ENJOY", "ENTER", "ENTRY",
            "EQUAL", "ERROR", "ESSAY", "EVENT", "EVERY", "EXACT", "EXERT",
            "EXILE", "EXIST", "EXTRA", "FABLE", "FACET", "FAINT", "FAIRY",
            "FAITH", "FALSE", "FANCY", "FATAL", "FAULT", "FEAST", "FENCE",
            "FEVER", "FIBER", "FIELD", "FIERY", "FIFTH", "FIFTY", "FIGHT",
            "FINAL", "FIRST", "FISHY", "FIXED", "FLAME", "FLASH", "FLEET",
            "FLESH", "FLOAT", "FLOOD", "FLOOR", "FLOUR", "FLUID", "FLUSH",
            "FLUTE", "FOCAL", "FOCUS", "FORCE", "FORGE", "FORKS", "FORMER",
            "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH",
            "FRONT", "FROST", "FROZE", "FRUIT", "GAUGE", "GHOST", "GIANT",
            "GIVEN", "GLARE", "GLEAM", "GLOBE", "GLOOM", "GLORY", "GLOSS",
            "GLOVE", "GRACE", "GRADE", "GRAIN", "GRAND", "GRAPH", "GRASP",
            "GRASS", "GRAVE", "GREAT", "GREED", "GREEN", "GREET", "GRIEF",
            "GRIND", "GROAN", "GROOM", "GROSS", "GROUP", "GROVE", "GUARD",
            "GUESS", "GUEST", "GUIDE", "GUILT", "HABIT", "HAIRY", "HAPPY",
            "HARDY", "HARSH", "HATCH", "HAUNT", "HAVEN", "HAVOC", "HEADY",
            "HEART", "HEAVY", "HEDGE", "HEIST", "HENCE", "HINGE", "HOBBY",
            "HONOR", "HORDE", "HORSE", "HOTEL", "HOUND", "HOUSE", "HOVER",
            "HUMAN", "HUMID", "HUMOR", "HURRY", "IDEAL", "IMAGE", "IMPLY",
            "INDEX", "INFER", "INNER", "INPUT", "IRONY", "ISSUE", "IVORY",
            "JEWEL", "JOINT", "JOKER", "JUDGE", "JUICE", "KHAKI", "KNEEL",
            "KNIFE", "KNOCK", "KNOWN", "LABEL", "LABOR", "LARGE", "LASER",
            "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAVE", "LEGAL",
            "LEMON", "LEVEL", "LEVER", "LIGHT", "LIMIT", "LINEN", "LIVER",
            "LOBBY", "LOCAL", "LODGE", "LOFTY", "LOGIC", "LOOSE", "LOVELY",
            "LOYAL", "LUCKY", "LUNAR", "LUNCH", "LYRIC", "MAGIC", "MAJOR",
            "MAKER", "MANOR", "MAPLE", "MARCH", "MARRY", "MARSH", "MASON",
            "MATCH", "MAYOR", "MEANT", "MEDAL", "MEDIA", "MERCY", "MERGE",
            "MERIT", "MERRY", "METAL", "METER", "MIGHT", "MINOR", "MINUS",
            "MIRTH", "MODEL", "MONEY", "MONTH", "MORAL", "MOTOR", "MOUNT",
            "MOUSE", "MOUTH", "MOVIE", "MUSIC", "NAIVE", "NAKED", "NEARBY",
            "NEEDLE", "NERVE", "NEVER", "NEWLY", "NIGHT", "NINTH", "NOBLE",
            "NOISE", "NORTH", "NOTED", "NOVEL", "NURSE", "NYLON", "OCCUR",
            "OCEAN", "OFFER", "OFTEN", "OLIVE", "ONION", "OPERA", "ORBIT",
            "ORDER", "ORGAN", "OTHER", "OUGHT", "OUTER", "OWNER", "OXIDE",
            "OZONE", "PAINT", "PANEL", "PANIC", "PAPER", "PARTY", "PASTA",
            "PASTE", "PATCH", "PAUSE", "PEACE", "PEARL", "PENAL", "PENCIL",
            "PEOPLE", "PERIOD", "PERMIT", "PERSON", "PETTY", "PHASE", "PHONE",
            "PHOTO", "PIANO", "PIECE", "PILOT", "PITCH", "PIZZA", "PLACE",
            "PLAIN", "PLANE", "PLANT", "PLATE", "PLAZA", "PLEAD", "PLUCK",
            "PLUMB", "PLUME", "PLUMP", "PLUNGE", "POEM", "POET", "POINT",
            "POLAR", "POLITE", "POND", "PONY", "POOL", "PORCH", "PORT",
            "POUND", "POWER", "PRAISE", "PRAY", "PRAYER", "PREACH", "PRESS",
            "PRICE", "PRIDE", "PRIME", "PRINCE", "PRINT", "PRIOR", "PRIZE",
            "PROBE", "PROOF", "PROSE", "PROUD", "PROVE", "PRUNE", "PULSE",
            "PUNCH", "PUPIL", "PUPPET", "PURCHASE", "PURPLE", "PURSE",
            "PUSH", "PUZZLE", "QUEEN", "QUERY", "QUEST", "QUEUE", "QUICK",
            "QUIET", "QUILT", "QUITE", "QUIZ", "QUOTA", "QUOTE", "RABBIT",
            "RADIO", "RAINY", "RAISE", "RALLY", "RANCH", "RANGE", "RAPID",
            "RATIO", "RAVEN", "REACH", "REACT", "READY", "REALM", "REBEL",
            "RECENT", "RECORD", "REDEEM", "REDUCE", "REFER", "REFINE",
            "REFORM", "REFUSE", "REGAL", "REGARD", "REGIME", "REGION",
            "REJECT", "RELATE", "RELAX", "RELIEF", "REMAIN", "REMEDY",
            "RENDER", "RENT", "REPAIR", "REPEAT", "REPLACE", "REPLY",
            "REPORT", "REQUEST", "RESCUE", "RESENT", "RESIGN", "RESIST",
            "RESOLVE", "RESORT", "REST", "RESTORE", "RESULT", "RETAIL",
            "RETAIN", "RETIRE", "RETURN", "REVEAL", "REVIEW", "REWARD",
            "RHYME", "RHYTHM", "RIDER", "RIDGE", "RIFLE", "RIGHT", "RIGID",
            "RIPEN", "RISKY", "RIVAL", "RIVER", "ROBIN", "ROBOT", "ROCKY",
            "ROGER", "ROMAN", "ROUGE", "ROUGH", "ROUND", "ROUTE", "ROYAL",
            "RUBBER", "RUDDY", "RUGBY", "RULER", "RURAL", "RUSTY", "SABLE",
            "SACRED", "SAFETY", "SAINT", "SALAD", "SALMON", "SALTY", "SAME",
            "SAMPLE", "SANDAL", "SANDY", "SATIN", "SAUCE", "SAUCY", "SAVING",
            "SAVOR", "SAVORY", "SCALE", "SCARE", "SCARF", "SCENE", "SCENT",
            "SCOLD", "SCOOP", "SCORE", "SCORN", "SCOUT", "SCRAP", "SCREEN",
            "SCREW", "SCRIPT", "SEAL", "SEARCH", "SEASON", "SECOND", "SECRET",
            "SECURE", "SEIZE", "SENATE", "SENIOR", "SENSE", "SERIES",
            "SERVE", "SERVICE", "SEVERE", "SHACK", "SHADE", "SHADOW",
            "SHAFT", "SHAKE", "SHALL", "SHAME", "SHAPE", "SHARE", "SHARK",
            "SHARP", "SHAVE", "SHEER", "SHEET", "SHELF", "SHELL", "SHIELD",
            "SHIFT", "SHINE", "SHINY", "SHIRT", "SHOCK", "SHORE", "SHORT",
            "SHOUT", "SHOVE", "SHRED", "SHRIMP", "SHRINE", "SHRINK",
            "SHRUB", "SHRUG", "SIGHT", "SILLY", "SILVER", "SIMPLE", "SIMPLY",
            "SINCE", "SINGLE", "SIXTH", "SIXTY", "SKATE", "SKETCH", "SKILL",
            "SKULL", "SLATE", "SLEEK", "SLEEP", "SLEET", "SLICE", "SLIDE",
            "SLIGHT", "SLIME", "SLING", "SLOPE", "SMALL", "SMART", "SMELL",
            "SMILE", "SMOKE", "SMOOTH", "SNAIL", "SNAKE", "SNARE", "SNARL",
            "SNEAK", "SNIFF", "SNOWY", "SNUG", "SOBER", "SOLAR", "SOLID",
            "SOLVE", "SONIC", "SORRY", "SOUND", "SOUTH", "SPACE", "SPADE",
            "SPARE", "SPARK", "SPEAK", "SPEAR", "SPEED", "SPELL", "SPEND",
            "SPICE", "SPICY", "SPIDER", "SPIKE", "SPINE", "SPIRIT", "SPLIT",
            "SPOKE", "SPOON", "SPORT", "SPOT", "SPRAY", "SPRING", "SQUAD",
            "SQUARE", "SQUASH", "SQUEAK", "STABLE", "STACK", "STAFF",
            "STAGE", "STAIR", "STAKE", "STALE", "STALK", "STALL", "STAMP",
            "STAND", "STAR", "STARE", "STARK", "START", "STARVE", "STATE",
            "STATUS", "STEADY", "STEAK", "STEAL", "STEAM", "STEEL", "STEEP",
            "STEER", "STICK", "STIFF", "STILL", "STING", "STOCK", "STONE",
            "STOOD", "STOOL", "STORE", "STORM", "STORY", "STOUT", "STOVE",
            "STRANGE", "STRAW", "STREAM", "STREET", "STRICT", "STRING",
            "STRIP", "STRIPE", "STRONG", "STUCK", "STUDY", "STUFF", "STYLE",
            "SUBJECT", "SUBMIT", "SUBTLE", "SUGAR", "SUIT", "SULKY",
            "SUMMER", "SUNNY", "SUPER", "SUPPER", "SURE", "SURFACE",
            "SURGE", "SURVEY", "SWALLOW", "SWAMP", "SWARM", "SWAY",
            "SWEAR", "SWEAT", "SWEEP", "SWEET", "SWELL", "SWIFT", "SWING",
            "SWIRL", "SWITCH", "SWORD", "SYMBOL", "SYSTEM", "TABLE",
            "TACKLE", "TAIL", "TASTE", "TASTY", "TEACH", "TEAM", "TEMPER",
            "TEMPTER", "TEND", "TENDER", "TENNIS", "TENSE", "TERM",
            "TERRAIN", "TERRIBLE", "TERROR", "TEST", "TEXT", "THEFT",
            "THEME", "THICK", "THIEF", "THIGH", "THING", "THINK", "THIRD",
            "THORN", "THREAD", "THREAT", "THRILL", "THRIVE", "THROAT",
            "THRONE", "THROW", "THUMB", "TICKET", "TIGER", "TIGHT",
            "TIMBER", "TITLE", "TOAST", "TODAY", "TOKEN", "TOMATO",
            "TONGUE", "TOOTH", "TOPIC", "TORCH", "TOTAL", "TOUCH", "TOUGH",
            "TOWEL", "TOWER", "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL",
            "TRAIN", "TRASH", "TRAVEL", "TREAT", "TREND", "TRIAL", "TRIBE",
            "TRICK", "TRIM", "TRIP", "TROOP", "TROPHY", "TROUBLE", "TRUCK",
            "TRULY", "TRUNK", "TRUST", "TRUTH", "TUMBLER", "TURKEY",
            "TURN", "TURTLE", "TWELVE", "TWENTY", "TWICE", "TWIN", "TWIST",
            "UDDER", "UNCLE", "UNDER", "UNIQUE", "UNITE", "UNITY", "UNLESS",
            "UNLIKE", "UNLOAD", "UNLOCK", "UPDATE", "UPGRADE", "UPHOLD",
            "UPPER", "UPSET", "URBAN", "URINE", "USAGE", "USHER", "USUAL",
            "UTTER", "VACANT", "VACUUM", "VAGUE", "VALID", "VALUE", "VALVE",
            "VANISH", "VAPOR", "VAULT", "VEGAN", "VEHICLE", "VELVET",
            "VENTURE", "VERSE", "VERSION", "VESSEL", "VETERAN", "VICTIM",
            "VICTORY", "VIDEO", "VIEW", "VILLAGE", "VINTAGE", "VIOLET",
            "VIRTUE", "VISION", "VISIT", "VISUAL", "VITAL", "VIVID",
            "VOCAL", "VOICE", "VOLUME", "VOTER", "VOWEL", "VOYAGE",
            "WAGON", "WASTE", "WATCH", "WATER", "WEALTH", "WEAPON",
            "WEARY", "WEAVE", "WEDGE", "WEIRD", "WHEAT", "WHEEL", "WHERE",
            "WHICH", "WHILE", "WHITE", "WHOLE", "WIDEN", "WIDOW", "WIDTH",
            "WINDOW", "WINTER", "WISDOM", "WITCH", "WITHIN", "WOMAN",
            "WONDER", "WOODEN", "WORLD", "WORRY", "WORSE", "WORST",
            "WORTH", "WOULD", "WOUND", "WRATH", "WRIST", "WRITER",
            "WRONG", "YACHT", "YELLOW", "YIELD", "YOUNG", "YOUTH",
            "ZEBRA", "ZESTY",
            # 6-letter
            "ABDUCT", "ABJECT", "ABROAD", "ABSORB", "ACCEPT", "ACCESS",
            "ACROSS", "ACTION", "ACTIVE", "ACTUAL", "ADVICE", "ADVISE",
            "AFFECT", "AFFORD", "AFRAID", "AGENCY", "AGENDA", "ALMOST",
            "ALWAYS", "AMOUNT", "ANIMAL", "ANNUAL", "ANSWER", "ANYWAY",
            "APPEAL", "APPEAR", "AROUND", "ARREST", "ARRIVE", "ARTIST",
            "ASSERT", "ASSIGN", "ASSIST", "ASSOCIATE", "ASSUME", "ASSURE",
            "ATTACH", "ATTACK", "ATTEND", "AUGUST", "AUTHOR", "AVENUE",
            "BANKER", "BANNER", "BARREL", "BASKET", "BATTLE", "BEAUTY",
            "BECOME", "BEFORE", "BEHAVE", "BEHIND", "BELIEF", "BELONG",
            "BENEFIT", "BESIDE", "BEYOND", "BISHOP", "BITTER", "BLAZER",
            "BORDER", "BORROW", "BOTTLE", "BOTTOM", "BOUGHT", "BRANCH",
            "BREACH", "BREATH", "BRIDGE", "BRIGHT", "BROKEN", "BRONZE",
            "BROWSER", "BRUTAL", "BUBBLE", "BUCKET", "BUDGET", "BURDEN",
            "BUREAU", "BUTTER", "BUTTON", "CABINET", "CAMPUS", "CANCEL",
            "CAPTURE", "CARBON", "CAREER", "CARPET", "CASTLE", "CATCH",
            "CAUSAL", "CAUTION", "CEILING", "CENTRAL", "CENTURY", "CHAMBER",
            "CHANNEL", "CHAPTER", "CHARGE", "CHASER", "CHEESE", "CHERRY",
            "CHOICE", "CHOOSE", "CHOSEN", "CHURCH", "CIRCLE", "CLIENT",
            "CLOSED", "CLOSER", "COFFEE", "COLUMN", "COMBAT", "COMEDY",
            "COMMAND", "COMMENT", "COMMIT", "COMMON", "COMPANY", "COMPEL",
            "COMPOSE", "CONCEPT", "CONCERN", "CONDUCT", "CONFIRM", "CONNECT",
            "CONSENT", "CONSIST", "CONTAIN", "CONTENT", "CONTEXT",
            "CONTROL", "CONVERT", "CONVEY", "COOKIE", "CORNER", "COSTLY",
            "COTTAGE", "COUNSEL", "COUNTER", "COUNTRY", "COUPLE",
            "COURAGE", "COUSIN", "COVERAGE", "CRADLE", "CRAFTS", "CREATE",
            "CREATURE", "CREDIT", "CRISIS", "CRITIC", "CRUISE", "CRYSTAL",
            "CULTURE", "CURRENT", "CUSTOMS", "DANGER", "DARKEN", "DEALER",
            "DEARTH", "DEBATE", "DEBRIS", "DECADE", "DECIDE", "DECLARE",
            "DECLINE", "DECORATE", "DECREE", "DEDUCT", "DEFEAT", "DEFEND",
            "DEFINE", "DEGREE", "DELAY", "DELIGHT", "DELIVER", "DEMAND",
            "DEMOCRAT", "DENIAL", "DENOTE", "DENTAL", "DENY", "DEPART",
            "DEPEND", "DEPICT", "DEPLOY", "DEPOSIT", "DEPRESS", "DERIVE",
            "DESCEND", "DESERT", "DESERVE", "DESIRE", "DESPITE",
            "DESTROY", "DETAIL", "DETAIN", "DETECT", "DETER", "DEVELOP",
            "DEVICE", "DEVOTE", "DEVOUR", "DIALOG", "DIAMOND", "DINNER",
            "DIRECT", "DIVIDE", "DIVINE", "DOCTOR", "DOMAIN", "DOUBLE",
            "DRAGON", "DRIVER", "DYNAMIC", "EARNEST", "EASIER", "EDITOR",
            "EFFECT", "EFFORT", "EIGHTH", "ELDERLY", "ELEMENT", "EMERGE",
            "EMPIRE", "EMPLOY", "EMPTY", "ENABLE", "ENDING", "ENDLESS",
            "ENDORSE", "ENDURE", "ENERGY", "ENGAGE", "ENGINE", "ENHANCE",
            "ENJOY", "ENORMOUS", "ENSURE", "ENTIRE", "ENTITY", "ENTRY",
            "ENVELOPE", "EPISODE", "EQUAL", "EQUIP", "EQUITY", "ERROR",
            "ESCAPE", "ESSAY", "ESTATE", "ETHNIC", "EVALUATE", "EVENLY",
            "EVENT", "EVERY", "EVIDENCE", "EVOLVE", "EXACT", "EXAMINE",
            "EXAMPLE", "EXCEED", "EXCEPT", "EXCHANGE", "EXCITE", "EXCUSE",
            "EXEMPT", "EXERCISE", "EXHIBIT", "EXIST", "EXIT", "EXPAND",
            "EXPECT", "EXPENSE", "EXPERT", "EXPLAIN", "EXPLODE", "EXPLOIT",
            "EXPLORE", "EXPORT", "EXPOSE", "EXTEND", "EXTENT", "EXTERNAL",
            "EXTRACT", "EXTREME", "FABRIC", "FACIAL", "FACTOR", "FAMILY",
            "FAMOUS", "FARMER", "FATHER", "FATIGUE", "FAULTY", "FAVOR",
            "FEATURE", "FEBRUARY", "FEDERAL", "FEEDBACK", "FEMALE",
            "FESTIVAL", "FIERCE", "FIGHTER", "FILLED", "FILTER", "FINAL",
            "FINANCE", "FINGER", "FINISH", "FISCAL", "FITNESS", "FLAVOR",
            "FLEEING", "FLEXIBLE", "FLIGHT", "FLOATING", "FLOCK",
            "FLOODED", "FLOWERS", "FLUID", "FLYING", "FOCUS", "FOLLOW",
            "FORBID", "FORCE", "FOREIGN", "FOREST", "FORGET", "FORMAL",
            "FORMAT", "FORMER", "FOSTER", "FOUGHT", "FOUND", "FOUNDER",
            "FRACTION", "FRAME", "FRAMEWORK", "FRANKLY", "FRAUD",
            "FREEDOM", "FREQUENT", "FRESHLY", "FRIEND", "FRINGE", "FRONT",
            "FROZEN", "FRUITS", "FULFILL", "FUNCTION", "FUNDING", "FUNERAL",
            "FURIOUS", "FURNITURE", "FURTHER", "GALAXY", "GALLERY",
            "GAMBLE", "GANGER", "GARDEN", "GARLIC", "GARMENT", "GATHER",
            "GENDER", "GENERAL", "GENIUS", "GENRE", "GENTLE", "GENUINE",
            "GESTURE", "GIANT", "GIFTED", "GLOBAL", "GOLDEN", "GOVERN",
            "GRACEFUL", "GRADE", "GRADUAL", "GRAND", "GRANT", "GRAPHIC",
            "GRAVITY", "GREATER", "GREEDY", "GREETINGS", "GRIEVOUS",
            "GROCERY", "GROUND", "GROUP", "GROWTH", "GUARDIAN", "GUESS",
            "GUEST", "GUIDE", "GUILTY", "GUNNING", "HABITAT", "HALF",
            "HANDLE", "HAPPEN", "HARBOR", "HARDEN", "HARDLY", "HARMONY",
            "HARSH", "HARVEST", "HASTEN", "HATRED", "HAVING", "HAZARD",
            "HEALING", "HEALTHY", "HEARING", "HEARTY", "HEAVENLY",
            "HEAVILY", "HEIGHT", "HELPFUL", "HERSELF", "HIDDEN", "HIGHLY",
            "HIGHWAY", "HIMSELF", "HINDRANCE", "HISTORY", "HOLDER",
            "HOLIDAY", "HONEST", "HONEYMOON", "HONORABLE", "HORIZON",
            "HORROR", "HOSTILE", "HOTEL", "HUNGRY", "HUNTER", "HUSBAND",
            "HYBRID", "IGNORE", "ILLEGAL", "ILLNESS", "IMAGE", "IMAGINE",
            "IMMENSE", "IMPACT", "IMPERIAL", "IMPLANT", "IMPLY",
            "IMPORT", "IMPOSE", "IMPRESS", "IMPROVE", "IMPULSE",
            "INCIDENT", "INCLUDE", "INCOME", "INCREASE", "INDEED",
            "INDEX", "INDICATE", "INDOOR", "INDUCE", "INDUSTRY",
            "INFANT", "INFLICT", "INFORM", "INHALE", "INITIAL",
            "INJECT", "INJURY", "INMATE", "INNER", "INNOCENT", "INPUT",
            "INQUIRY", "INSECT", "INSERT", "INSIDE", "INSIGHT", "INSIST",
            "INSPECT", "INSTALL", "INSTANT", "INSTEAD", "INTACT",
            "INTEND", "INTENSE", "INTENT", "INTERACT", "INTEREST",
            "INTERNAL", "INTERVAL", "INTRODUCE", "INVADE", "INVENT",
            "INVEST", "INVITE", "INVOKE", "INVOLVE", "IRONIC", "ISSUE",
            "ISLAND", "ISOLATE", "ITSELF", "JEALOUS", "JUNGLE", "JUNIOR",
            "JUSTICE", "JUSTIFY", "KENNEL", "KIDNAP", "KILLER", "KINDNESS",
            "KITCHEN", "KNIGHT", "LABEL", "LABOR", "LADDER", "LAMENT",
            "LANTERN", "LAPTOP", "LARGELY", "LASER", "LASTING", "LATTER",
            "LAUGHTER", "LAUNCH", "LAWYER", "LAYOUT", "LEADER", "LEAGUE",
            "LEARNER", "LECTURE", "LEGACY", "LEGEND", "LENGTH", "LESSON",
            "LETHAL", "LETTER", "LEVEL", "LIBERAL", "LIBRARY", "LICENSE",
            "LIGHTER", "LIKELY", "LIMIT", "LINEAR", "LINING", "LIQUID",
            "LISTEN", "LITERAL", "LITTLE", "LIVELY", "LIVING", "LOADED",
            "LOBBY", "LOCAL", "LOCATE", "LOCKER", "LOGIC", "LONELY",
            "LONGING", "LOOSELY", "LORD", "LOSING", "LOSS", "LOVELY",
            "LOVER", "LOWEST", "LUCKILY", "LUMBER", "LUXURY",
            "MACHINE", "MADAME", "MAGAZINE", "MAGNET", "MAINTAIN",
            "MAJORITY", "MAKER", "MANAGE", "MANNER", "MANSION", "MANUAL",
            "MARBLE", "MARGIN", "MARINE", "MARKER", "MARKET", "MARTIAL",
            "MASTER", "MATCH", "MATTER", "MATURE", "MAXIMUM", "MAYOR",
            "MEADOW", "MEANING", "MEASURE", "MEDAL", "MEDIA", "MEDICAL",
            "MEMBER", "MEMORY", "MENTAL", "MENTION", "MERCY", "MERELY",
            "MERGER", "MERIT", "MESSAGE", "METHOD", "METRIC", "MIDDLE",
            "MIGHTY", "MILITARY", "MILLION", "MINERAL", "MINIMAL",
            "MINIMUM", "MINORITY", "MINUTE", "MIRROR", "MISERY",
            "MISSION", "MISTAKE", "MIXTURE", "MODEL", "MODERATE",
            "MODERN", "MODEST", "MODIFY", "MODULE", "MOMENT", "MONITOR",
            "MONTHLY", "MORALE", "MORTAL", "MOSAIC", "MOTHER", "MOTION",
            "MOTIVE", "MOTOR", "MOUNT", "MOUNTAIN", "MOUSE", "MOVING",
            "MULTIPLE", "MURDER", "MUSCLE", "MUSEUM", "MUSICAL",
            "MUTUAL", "MYSTERY", "NARROW", "NATION", "NATIVE", "NATURE",
            "NEARBY", "NEARLY", "NECKLACE", "NEEDLE", "NEGATIVE",
            "NEGLECT", "NEITHER", "NERVOUS", "NETWORK", "NEUTRAL",
            "NINTH", "NOBODY", "NORMAL", "NOTABLE", "NOTHING", "NOTICE",
            "NOTION", "NOVEL", "NUCLEAR", "NUMBER", "NURSE", "OBJECT",
            "OBSERVE", "OBTAIN", "OCCASION", "OCCUPY", "OFFENSE",
            "OFFICER", "OFFICIAL", "OFTEN", "ONLINE", "ONLY", "OPENER",
            "OPENLY", "OPERATE", "OPINION", "OPPOSE", "OPTION", "ORANGE",
            "ORBIT", "ORCHARD", "ORDER", "ORDINARY", "ORGANIC", "ORIGIN",
            "ORNAMENT", "OTHER", "OUTBREAK", "OUTCOME", "OUTDOOR",
            "OUTER", "OUTLINE", "OUTPUT", "OUTSIDE", "OVERALL",
            "OWNERSHIP", "OXYGEN", "PACKAGE", "PADDLE", "PAGEANT",
            "PAINFUL", "PAINTING", "PALACE", "PAMPHLET", "PANEL",
            "PANIC", "PAPER", "PARADE", "PARENT", "PARISH", "PARKING",
            "PARTIAL", "PARTICLE", "PARTLY", "PARTNER", "PARTY",
            "PASSAGE", "PASSION", "PASSIVE", "PASTURE", "PATCH",
            "PATIENT", "PATROL", "PATTERN", "PAUSE", "PAYMENT",
            "PEACE", "PEANUT", "PECULIAR", "PENALTY", "PENDING",
            "PENETRATE", "PENSION", "PEOPLE", "PERCENT", "PERFECT",
            "PERFORM", "PERFUME", "PERHAPS", "PERIOD", "PERMIT",
            "PERSON", "PERSUADE", "PETROL", "PHANTOM", "PHASE",
            "PHENOMENON", "PHILOSOPHY", "PHONE", "PHOTO", "PHRASE",
            "PHYSICAL", "PIANO", "PICKLE", "PICTURE", "PIERCE",
            "PIGEON", "PILLAR", "PILLOW", "PILOT", "PINEAPPLE",
            "PIONEER", "PISTOL", "PIVOTAL", "PLACID", "PLAGUE",
            "PLANET", "PLANT", "PLASTIC", "PLATEAU", "PLAYER",
            "PLEASE", "PLEDGE", "PLENTY", "PLOT", "PLUNGE", "POCKET",
            "POEM", "POETRY", "POINT", "POISON", "POLAR", "POLICE",
            "POLICY", "POLISH", "POLITE", "POLLUTE", "PONDER",
            "POPULAR", "PORCH", "PORTAL", "PORTION", "PORTRAIT",
            "POSITION", "POSITIVE", "POSSESS", "POSSIBLE", "POSTAL",
            "POSTURE", "POTATO", "POTENTIAL", "POUND", "POVERTY",
            "POWDER", "POWER", "PRACTICE", "PRAIRIE", "PRAISE",
            "PRAYER", "PRECISE", "PREDICT", "PREFER", "PREMIER",
            "PREMIUM", "PREPARE", "PRESCRIBE", "PRESENCE", "PRESENT",
            "PRESERVE", "PRESIDE", "PRESS", "PRESSURE", "PRESTIGE",
            "PRETEND", "PRETTY", "PREVAIL", "PREVENT", "PREVIOUS",
            "PRICE", "PRIDE", "PRIMARY", "PRINCE", "PRINCIPAL",
            "PRINCIPLE", "PRINT", "PRIORITY", "PRISON", "PRIVACY",
            "PRIVATE", "PRIZE", "PROBLEM", "PROCEED", "PROCESS",
            "PRODUCE", "PRODUCT", "PROFESS", "PROFILE", "PROFIT",
            "PROGRAM", "PROJECT", "PROMISE", "PROMOTE", "PROMPT",
            "PROOF", "PROPER", "PROPERTY", "PROPHET", "PROPORTION",
            "PROPOSAL", "PROPOSE", "PROSECUTE", "PROSPECT", "PROTECT",
            "PROTEIN", "PROTEST", "PROUD", "PROVE", "PROVIDE",
            "PROVINCE", "PROVOKE", "PROXY", "PSALM", "PUBLIC",
            "PUBLISH", "PULLEY", "PULSE", "PUNCH", "PUNISH",
            "PURCHASE", "PURITY", "PURPLE", "PURPOSE", "PURSUE",
            "PURSUIT", "PUZZLE", "PYRAMID", "QUALIFY", "QUALITY",
            "QUANTUM", "QUARREL", "QUARTER", "QUEEN", "QUESTION",
            "QUICKLY", "QUIETLY", "QUILT", "QUIT", "QUITE", "QUOTA",
            "RABBIT", "RACIAL", "RADICAL", "RADIO", "RAGE", "RAID",
            "RAILROAD", "RALLY", "RANCH", "RANDOM", "RANGE", "RAPID",
            "RARE", "RARELY", "RATIO", "RATIONAL", "RAVEN", "RAZOR",
            "REACH", "REACT", "READER", "READILY", "READING",
            "REALITY", "REALIZE", "REALM", "REAR", "REASON",
            "REASSURE", "REBEL", "RECALL", "RECENT", "RECESS",
            "RECIPE", "RECKON", "RECORD", "RECOVER", "RECRUIT",
            "REDUCE", "REFER", "REFINE", "REFLECT", "REFORM",
            "REFUGEE", "REFUSE", "REGARD", "REGIME", "REGION",
            "REGISTER", "REGRET", "REGULAR", "REJECT", "RELATE",
            "RELEASE", "RELENTLESS", "RELIABLE", "RELIEF", "RELY",
            "REMAIN", "REMARK", "REMEDY", "REMEMBER", "REMIND",
            "REMOTE", "REMOVAL", "REMOVE", "RENDER", "RENTAL",
            "REPAIR", "REPEAT", "REPLACE", "REPLY", "REPORT",
            "REQUEST", "REQUIRE", "RESCUE", "RESENT", "RESERVE",
            "RESIDE", "RESIGN", "RESIST", "RESOLVE", "RESORT",
            "RESOURCE", "RESPOND", "RESTORE", "RESULT", "RETAIL",
            "RETAIN", "RETIRE", "RETURN", "REVEAL", "REVENUE",
            "REVERSE", "REVIEW", "REVOLT", "REWARD", "RHYTHM",
            "RHYTHMIC", "RIBBON", "RICHES", "RIDDEN", "RIDDLE",
            "RIDER", "RIDGE", "RIFLE", "RIGOR", "RIM", "RING",
            "RINSE", "RIPEN", "RISING", "RISK", "RITE", "RITUAL",
            "RIVAL", "RIVER", "ROAD", "ROAR", "ROBIN", "ROBOT",
            "ROCK", "ROCKET", "ROD", "RODE", "ROGER", "ROLE",
            "ROLLER", "ROMAN", "ROMANCE", "ROMANTIC", "ROOF",
            "ROOM", "ROOT", "ROSARY", "ROSE", "ROTARY", "ROTATE",
            "ROTOR", "ROUGE", "ROUGH", "ROUND", "ROUSE",
            "ROUTINE", "ROVER", "ROW", "ROYAL", "RUBBER", "RUGGED",
            "RUIN", "RULER", "RUNNER", "RURAL", "RUSH", "RUST",
            "RUSTIC", "SABER", "SACK", "SACRED", "SADDLE",
            "SAFARI", "SAFETY", "SAILOR", "SAINT", "SAKE",
            "SALAD", "SALARY", "SALE", "SALMON", "SALON", "SALT",
            "SALUTE", "SALVAGE", "SAMPLE", "SANCTUARY", "SANDAL",
            "SANDBOX", "SANE", "SARCASM", "SASH", "SATELLITE",
            "SATIN", "SATIRE", "SAUCE", "SAVAGE", "SAVING",
            "SAVOR", "SAVORY", "SAW", "SCALE", "SCAN", "SCANDAL",
            "SCARCE", "SCARE", "SCARF", "SCENE", "SCENT",
            "SCHEME", "SCHOLAR", "SCHOOL", "SCIENCE", "SCISSORS",
            "SCOLD", "SCOOP", "SCORE", "SCORN", "SCOUT", "SCRAMBLE",
            "SCRAP", "SCREEN", "SCREW", "SCRIPT", "SCRUTINY",
            "SCULPTURE", "SEAL", "SEAM", "SEARCH", "SEASON",
            "SEAT", "SECLUDED", "SECOND", "SECRET", "SECTION",
            "SECURE", "SEED", "SEEK", "SEGMENT", "SEIZE",
            "SELL", "SEMESTER", "SEMINAR", "SENATE", "SENIOR",
            "SENSE", "SENTENCE", "SEPARATE", "SEQUENCE", "SERENE",
            "SERIES", "SERIOUS", "SERVE", "SESSION", "SETTLE",
            "SETUP", "SEVENTH", "SEVERE", "SHACKLE", "SHADOW",
            "SHAFT", "SHALL", "SHAME", "SHAPE", "SHARE",
            "SHARK", "SHARP", "SHAVE", "SHAWL", "SHEAR",
            "SHED", "SHEER", "SHEET", "SHELTER", "SHELVE",
            "SHIELD", "SHIFT", "SHINE", "SHIP", "SHIRT",
            "SHOCK", "SHOE", "SHOOT", "SHOP", "SHORE",
            "SHORTAGE", "SHORTS", "SHOULDER", "SHOUT", "SHOW",
            "SHOWER", "SHRED", "SHRIMP", "SHRINE", "SHRINK",
            "SHRUB", "SHRUG", "SHUTTER", "SHUTTLE", "SICKLE",
            "SIDEWAYS", "SIEGE", "SIGH", "SIGHT", "SIGNAL",
            "SILENCE", "SILENT", "SILK", "SILLY", "SILVER",
            "SIMPLE", "SIMPLIFY", "SIMPLY", "SINCERE", "SINGLE",
            "SINK", "SIP", "SISTER", "SITUATE", "SIXTEEN",
            "SIXTH", "SIXTY", "SIZE", "SKATE", "SKELETON",
            "SKETCH", "SKI", "SKILL", "SKIM", "SKIN",
            "SKIP", "SKIRT", "SKULL", "SKY", "SLACK",
            "SLAM", "SLANG", "SLAP", "SLASH", "SLATE",
            "SLAVE", "SLEEP", "SLEEVE", "SLICE", "SLIDE",
            "SLIGHT", "SLIM", "SLIP", "SLIT", "SLOGAN",
            "SLOPE", "SLOT", "SLOWLY", "SLUG", "SLUMP",
            "SMALL", "SMART", "SMELL", "SMILE", "SMOKE",
            "SMOOTH", "SNAKE", "SNAP", "SNEAK", "SNIFF",
            "SNOW", "SNUG", "SOAK", "SOAP", "SOAR",
            "SOBER", "SOCIAL", "SOCK", "SODA", "SOFA",
            "SOFTEN", "SOIL", "SOLAR", "SOLDIER", "SOLEMN",
            "SOLID", "SOLITARY", "SOLO", "SOLUTION", "SOLVE",
            "SOMEHOW", "SOMEONE", "SOMETHING", "SOMETIME", "SOMEWHAT",
            "SONG", "SOON", "SOOTHE", "SORE", "SORROW",
            "SORRY", "SORT", "SOUL", "SOUND", "SOUP",
            "SOURCE", "SOUTH", "SOVEREIGN", "SPACE", "SPADE",
            "SPAN", "SPARE", "SPARK", "SPEAK", "SPEAR",
            "SPECIAL", "SPECIES", "SPEECH", "SPEED", "SPELL",
            "SPEND", "SPHERE", "SPICE", "SPIDER", "SPIKE",
            "SPILL", "SPIN", "SPINE", "SPIRIT", "SPIT",
            "SPLASH", "SPLENDID", "SPLIT", "SPOKE", "SPOON",
            "SPORT", "SPOT", "SPRAY", "SPREAD", "SPRING",
            "SPRINT", "SQUAD", "SQUARE", "SQUASH", "SQUEAK",
            "SQUEEZE", "STABLE", "STACK", "STADIUM", "STAFF",
            "STAGE", "STAIR", "STAKE", "STALE", "STALK",
            "STALL", "STAMP", "STANCE", "STAND", "STAPLE",
            "STAR", "STARE", "STARK", "START", "STARVE",
            "STATE", "STATUS", "STATUTE", "STAY", "STEADY",
            "STEAK", "STEAL", "STEAM", "STEEL", "STEEP",
            "STEER", "STEM", "STEP", "STICK", "STIFF",
            "STILL", "STING", "STIR", "STITCH", "STOCK",
            "STONE", "STOOD", "STOOL", "STOP", "STORE",
            "STORM", "STORY", "STOUT", "STOVE", "STRANGE",
            "STRANGER", "STRAP", "STRAW", "STREAM", "STREET",
            "STRENGTH", "STRESS", "STRETCH", "STRICT", "STRIDE",
            "STRIKE", "STRING", "STRIP", "STRIPE", "STRIVE",
            "STROKE", "STRONG", "STRUCTURE", "STRUGGLE", "STUBBORN",
            "STUCK", "STUDENT", "STUDIO", "STUDY", "STUFF",
            "STUMBLE", "STUN", "STUPID", "STURDY", "STYLE",
            "SUBJECT", "SUBMIT", "SUBTLE", "SUBURB", "SUCCEED",
            "SUCCESS", "SUCK", "SUDDEN", "SUFFER", "SUGAR",
            "SUGGEST", "SUIT", "SULKY", "SUMMER", "SUMMIT",
            "SUNNY", "SUPER", "SUPPER", "SUPPLY", "SUPPORT",
            "SUPPOSE", "SUPREME", "SURE", "SURFACE", "SURGE",
            "SURGERY", "SURPLUS", "SURRENDER", "SURROUND", "SURVEY",
            "SURVIVE", "SUSPECT", "SUSPEND", "SUSTAIN", "SWALLOW",
            "SWAMP", "SWAN", "SWAP", "SWARM", "SWAY",
            "SWEAR", "SWEAT", "SWEATER", "SWEEP", "SWEET",
            "SWELL", "SWIFT", "SWIM", "SWING", "SWIRL",
            "SWITCH", "SWORD", "SYMBOL", "SYMPTOM", "SYSTEM",
            "TABLE", "TABOO", "TACKLE", "TACTIC", "TAILOR",
            "TALENT", "TALK", "TAME", "TANK", "TAP",
            "TAPE", "TARGET", "TARIFF", "TASK", "TASTE",
            "TASTY", "TAX", "TAXI", "TEACH", "TEAM",
            "TEAR", "TEASE", "TEETH", "TELL", "TEMPER",
            "TEMPLE", "TENANT", "TEND", "TENDER", "TENNIS",
            "TENSION", "TENT", "TERM", "TERMINAL", "TERMS",
            "TERRAIN", "TERRACE", "TERRIBLE", "TERROR", "TEST",
            "TEXT", "TEXTURE", "THANK", "THEME", "THEN",
            "THEORY", "THERAPY", "THERE", "THICK", "THIEF",
            "THIGH", "THIN", "THING", "THINK", "THIRD",
            "THIRST", "THORN", "THOROUGH", "THOSE", "THOUGH",
            "THREAD", "THREAT", "THRILL", "THRIVE", "THROAT",
            "THRONE", "THROUGH", "THROW", "THRUST", "THUMB",
            "THUNDER", "TICKET", "TIDE", "TIDY", "TIE",
            "TIGER", "TIGHT", "TILE", "TIMBER", "TIME",
            "TIMID", "TINY", "TIP", "TIRE", "TISSUE",
            "TITLE", "TOAST", "TOBACCO", "TODAY", "TOILET",
            "TOKEN", "TOLERATE", "TOLL", "TOMATO", "TOMORROW",
            "TONE", "TONGUE", "TONIGHT", "TOOL", "TOOTH",
            "TOPIC", "TORCH", "TORN", "TORTURE", "TOSS",
            "TOTAL", "TOUCH", "TOUGH", "TOUR", "TOURIST",
            "TOWEL", "TOWER", "TOWN", "TOXIC", "TOY",
            "TRACE", "TRACK", "TRADE", "TRAFFIC", "TRAIL",
            "TRAIN", "TRANSFER", "TRANSFORM", "TRANSIT", "TRANSITION",
            "TRANSLATE", "TRANSPORT", "TRASH", "TRAVEL", "TRAY",
            "TREAT", "TREATMENT", "TREATY", "TREE", "TREMBLE",
            "TREND", "TRIAL", "TRIBE", "TRICK", "TRIGGER",
            "TRIM", "TRIO", "TRIP", "TRIUMPH", "TRIVIAL",
            "TROOP", "TROPHY", "TROT", "TROUBLE", "TRUCK",
            "TRUE", "TRULY", "TRUNK", "TRUST", "TRUTH",
            "TRY", "TUBE", "TUCK", "TUMBLE", "TUNE",
            "TUNNEL", "TURKEY", "TURN", "TURTLE", "TUTOR",
            "TWICE", "TWIN", "TWIST", "TWO", "TYPE",
            "TYRANNY", "UGLY", "UNANIMOUS", "UNCLE", "UNCOVER",
            "UNDER", "UNDERGO", "UNDERMINE", "UNDERSTAND", "UNDERWEAR",
            "UNDO", "UNFOLD", "UNIFORM", "UNION", "UNIQUE",
            "UNIT", "UNITE", "UNITY", "UNIVERSE", "UNKNOWN",
            "UNLESS", "UNLIKE", "UNLOAD", "UNLOCK", "UNUSUAL",
            "UNVEIL", "UPDATE", "UPGRADE", "UPHOLD", "UPRIGHT",
            "UPSET", "UPWARD", "URBAN", "URGE", "URGENT",
            "USAGE", "USHER", "USUAL", "UTILITY", "UTTER",
            "VACANT", "VACUUM", "VAGUE", "VALID", "VALLEY",
            "VALUABLE", "VALUE", "VALVE", "VANISH", "VARIABLE",
            "VARIETY", "VARIOUS", "VARY", "VAST", "VEHICLE",
            "VELOCITY", "VELVET", "VENTURE", "VERB", "VERDICT",
            "VERIFY", "VERSION", "VERSUS", "VERTICAL", "VESSEL",
            "VETERAN", "VIABLE", "VIBRANT", "VICTIM", "VICTORY",
            "VIDEO", "VIEW", "VIGOR", "VILLAGE", "VINTAGE",
            "VIOLATE", "VIOLENCE", "VIOLET", "VIRTUAL", "VIRTUE",
            "VISION", "VISIT", "VISUAL", "VITAL", "VIVID",
            "VOCAL", "VOICE", "VOLUME", "VOLUNTEER", "VOTE",
            "VOTER", "VOWEL", "VOYAGE", "WAGE", "WAGON",
            "WAIT", "WAKE", "WALK", "WALLET", "WANDER",
            "WANT", "WAR", "WARD", "WARMTH", "WARN",
            "WARRANT", "WARRIOR", "WARY", "WASH", "WASTE",
            "WATCH", "WATER", "WAVE", "WAVY", "WAX",
            "WEAKEN", "WEALTH", "WEAPON", "WEAR", "WEARY",
            "WEATHER", "WEAVE", "WEDGE", "WEEKLY", "WEIGHT",
            "WEIRD", "WELCOME", "WELFARE", "WELL", "WESTERN",
            "WET", "WHALE", "WHEAT", "WHEEL", "WHERE",
            "WHICH", "WHILE", "WHIP", "WHISPER", "WHITE",
            "WHOLE", "WHOLESALE", "WHOSE", "WICKED", "WIDE",
            "WIDEN", "WIDOW", "WIDTH", "WIFE", "WILD",
            "WILL", "WILLING", "WIN", "WIND", "WINDOW",
            "WINE", "WING", "WIPE", "WIRE", "WISDOM",
            "WISE", "WITCH", "WITHIN", "WITNESS", "WOMAN",
            "WONDER", "WOODEN", "WORLD", "WORM", "WORRY",
            "WORSE", "WORSHIP", "WORST", "WORTH", "WORTHY",
            "WOULD", "WOUND", "WRAP", "WRATH", "WREAK",
            "WRENCH", "WRESTLE", "WRING", "WRIST", "WRITE",
            "WRITER", "WRONG", "YACHT", "YARD", "YARN",
            "YELLOW", "YIELD", "YOUNG", "YOUTH", "ZEAL",
            "ZEBRA", "ZERO", "ZEST", "ZONE",
        }

        for word in words:
            if self._valid_word(word):
                self._insert(word)
                self._word_count += 1

        logger.info("Loaded %d built-in words", self._word_count)

    def find_words(
        self, grid: List[List[str]]
    ) -> List[Tuple[str, List[Tuple[int, int]]]]:
        rows = len(grid)
        cols = len(grid[0]) if grid else 0
        results = set()
        paths = {}

        def dfs(
            r: int,
            c: int,
            node: TrieNode,
            visited: Set[Tuple[int, int]],
            path: List[Tuple[int, int]],
        ):
            ch = grid[r][c].upper()
            if ch not in node.children:
                return

            next_node = node.children[ch]
            visited.add((r, c))
            path.append((r, c))

            if next_node.is_end:
                word = "".join(grid[pr][pc] for pr, pc in path)
                if word not in results:
                    results.add(word)
                    paths[word] = list(path)

            directions = [
                (-1, -1), (-1, 0), (-1, 1),
                (0, -1),           (0, 1),
                (1, -1),  (1, 0),  (1, 1),
            ]

            for dr, dc in directions:
                nr, nc = r + dr, c + dc
                if 0 <= nr < rows and 0 <= nc < cols and (nr, nc) not in visited:
                    dfs(nr, nc, next_node, visited, path)

            visited.remove((r, c))
            path.pop()

        for r in range(rows):
            for c in range(cols):
                dfs(r, c, self._trie, set(), [])

        sorted_words = sorted(
            results, key=lambda w: (-len(w), w)
        )
        return [(w, paths[w]) for w in sorted_words]

    def words_on_grid(
        self, grid: List[List[str]]
    ) -> List[Tuple[str, List[Tuple[int, int]]]]:
        return self.find_words(grid)
